name: Deploy Terraform

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::237921648803:role/github-actions-terraform-role
          aws-region: ap-southeast-2

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
