name: Deploy/Destroy Failed Backup Notifications 

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action (Plan, Deploy, Destroy)'
        required: true
        default: 'apply'
      environments:
        description: 'Environment to target (EMEA, APAC, NAM, Test)'
        required: true
        default: 'Test'

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # Required for OIDC
      contents: read

    defaults:
      run:
        working-directory: terraform/env/${{ github.event.inputs.environments }}  # ✅ 

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::237921648803:role/github-actions-terraform-role
          aws-region: ap-southeast-2

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        if: github.event.inputs.action == 'Plan'
        run: terraform plan 

      - name: Terraform Apply
        if: github.event.inputs.action == 'Deploy'
        run: terraform apply -auto-approve 

      - name: Terraform Destroy
        if: github.event.inputs.action == 'Destroy'
        run: terraform destroy -auto-approve